server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoRitamDB
    username: autoRitam
    password: autoRitam
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true